# Generated by Django 4.2.16 on 2024-12-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='pickup_location',
            new_name='pickup_info',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='pickup_time',
        ),
        migrations.AddField(
            model_name='order',
            name='productid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.product'),
            preserve_default=False,
        ),
    ]
