# Generated by Django 4.2.16 on 2024-12-07 13:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_rename_pickup_location_transportation_pickup_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation',
            old_name='pickup_info',
            new_name='shipping_info',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='back.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('completed', '已支付')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '未完成'), ('completed', '已完成'), ('canceled', '取消')], default='未完成', max_length=20),
        ),
    ]
