# Generated by Django 4.2.16 on 2024-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_rename_pickup_info_transportation_shipping_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='status',
            field=models.CharField(choices=[('pending', '待发货'), ('in_transit', '已发货'), ('delivered', '已送达')], max_length=20),
        ),
    ]
