# Generated by Django 4.2.16 on 2024-12-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_transportation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
